apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  system: "examples"
  type:  "service"
  lifecycle: "experimental"
  owner: "guests"
metadata:
  name: "go-test"
  description: "dsdd"
  annotations:
    github.com/project-slug: cwiklik/go-test
    backstage.io/techdocs-ref: dir:.
    argocd/app-name: go-test-dev
    backstage.io/kubernetes-id: "go-test"
    sonarqube.org/project-key: "go-test"
    grafana/tag-selector: "Kubernetes"
    prometheus.io/rule: container_cpu_usage_seconds_total{namespace="go-test"}
    prometheus.io/alert: all
  tags:
    - golang
    - "examples"
    - "service"
    - "experimental"
  links:
    - url: https://go-test.
      title: Website
      icon: Website
    - url: https://grafana.diegoluisi.eti.br/
      title: Dashboard
      icon: dashboard
    - url: https://alerts.diegoluisi.eti.br/
      title: Alerts
      icon: alert
    - url: https://argocd.diegoluisi.eti.br/applications/go-test-dev?resource=
      title: ArgoCD
      icon: cloud
    - url: https://grafana.diegoluisi.eti.br/d/k8s_views_ns/kubernetes-views-namespaces?orgId=1&refresh=30s&var-datasource=Prometheus&var-namespace=go-test&var-resolution=30s
      title: Logs
      icon: cloud
    - url: https://kiali.diegoluisi.eti.br/kiali/console/graph/namespaces/?traffic=grpc%2CgrpcRequest%2Chttp%2ChttpRequest%2Ctcp%2CtcpSent&graphType=versionedApp&namespaces=go-test&duration=120&refresh=60000&idleNodes=true&layout=kiali-breadthfirst&namespaceLayout=kiali-dagre
      title: Kiali
      icon: cloud
